/**
 * Main-thread Sandkit API — composed from the `types/` submodule namespaces.
 */
export type SandkitApi = {
  action: typeof import("../../types/src/main/api/action").action;
  assets: typeof import("../../types/src/main/api/assets").assets;
  authorization: typeof import("../../types/src/main/api/authorization").authorization;
  building: typeof import("../../types/src/main/api/building").building;
  camera: typeof import("../../types/src/main/api/camera").camera;
  collector: typeof import("../../types/src/shared/api/collector").collector;
  cooldown: typeof import("../../types/src/main/api/cooldown").cooldown;
  discoveries: typeof import("../../types/src/main/api/discoveries").discoveries;
  effects: typeof import("../../types/src/main/api/effects").effects;
  elements: typeof import("../../types/src/main/api/elements").elements;
  energy: typeof import("../../types/src/main/api/energy").energy;
  events: typeof import("../../types/src/main/api/events").events;
  excavation: typeof import("../../types/src/main/api/excavation").excavation;
  fire: typeof import("../../types/src/shared/api/fire").fire;
  gameConfig: typeof import("../../types/src/main/api/gameconfig").gameConfig;
  grid: typeof import("../../types/src/main/api/grid").grid;
  hooks: typeof import("../../types/src/shared/api/hooks").hooks;
  i18n: typeof import("../../types/src/main/api/i18n").i18n;
  input: typeof import("../../types/src/main/api/input").input;
  items: typeof import("../../types/src/main/api/items").items;
  lights: typeof import("../../types/src/main/api/lights").lights;
  maps: typeof import("../../types/src/main/api/maps").maps;
  mods: typeof import("../../types/src/main/api/mods").mods;
  patterns: typeof import("../../types/src/shared/api/patterns").patterns;
  player: typeof import("../../types/src/main/api/player").player;
  processing: typeof import("../../types/src/main/api/processing").processing;
  progression: typeof import("../../types/src/main/api/progression").progression;
  projectiles: typeof import("../../types/src/main/api/projectiles").projectiles;
  random: typeof import("../../types/src/shared/api/random").random;
  raycast: typeof import("../../types/src/main/api/raycast").raycast;
  reactions: typeof import("../../types/src/main/api/reactions").reactions;
  rendering: typeof import("../../types/src/main/api/rendering").rendering;
  resources: typeof import("../../types/src/main/api/resources").resources;
  scene: typeof import("../../types/src/main/api/scene").scene;
  schedule: typeof import("../../types/src/main/api/schedule").schedule;
  settings: typeof import("../../types/src/main/api/settings").settings;
  shared: typeof import("../../types/src/main/api/shared").shared;
  signals: typeof import("../../types/src/main/api/signals").signals;
  sound: typeof import("../../types/src/main/api/sound").sound;
  sprites: typeof import("../../types/src/main/api/sprites").sprites;
  storage: typeof import("../../types/src/main/api/storage").storage;
  structureBehaviors: typeof import("../../types/src/main/api/structureBehaviors").structureBehaviors;
  structures: typeof import("../../types/src/main/api/structures").structures;
  tech: typeof import("../../types/src/main/api/tech").tech;
  terrains: typeof import("../../types/src/main/api/terrains").terrains;
  time: typeof import("../../types/src/main/api/time").time;
  tools: typeof import("../../types/src/main/api/tools").tools;
  triggers: typeof import("../../types/src/main/api/triggers").triggers;
  ui: typeof import("../../types/src/main/api/ui").ui;
  upgrades: typeof import("../../types/src/main/api/upgrades").upgrades;
  utils: typeof import("../../types/src/shared/api/utils").utils;
  workers: typeof import("../../types/src/main/api/workers").workers;
  world: typeof import("../../types/src/main/api/world").world;
};
